# .github/workflows/ci-cd.yml

# A name for your workflow. This will be displayed in the "Actions" tab of your GitHub repository.
name: React CI/CD Pipeline

# This section defines the trigger for the workflow.
# We want it to run on every 'push' to the 'main' branch.
on:
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # We'll define a single job called 'build-and-deploy'.
  build-and-deploy:
    # The type of virtual machine to run the job on. 'ubuntu-latest' is a good, standard choice.
    runs-on: ubuntu-latest

    # 'steps' represent a sequence of tasks that will be executed as part of the job.
    steps:
      # --- CI (Continuous Integration) Steps ---

      # Step 1: Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Sets up the Node.js environment.
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the node version to use. Use the one you develop with.
          cache: 'npm' # Caches npm packages for faster subsequent builds.

      # Step 3: Install project dependencies. 'npm ci' is recommended for CI as it's faster and more reliable than 'npm install'.
      - name: Install Dependencies
        run: npm ci

      # Step 4: Run the tests. The script is defined in package.json.
      # The '-- --coverage' is an example of passing args. The extra '--' is needed.
      # We'll also add CI=true to prevent tests from running in watch mode.
      - name: Run Tests
        run: npm test -- --watchAll=false
      
      # --- CD (Continuous Deployment) Steps ---

      # Step 5: Build the React application. This creates the 'build' folder.
      - name: Build Application
        run: npm run build

      # Step 6: Deploy the 'build' folder to the 'gh-pages' branch.
      # We use a popular, pre-made Action for this.
      - name of: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.